### PR TITLE
🏗️ Make codebase more streamlined

### PR DESCRIPTION
**Pull request by furtidev**
The commits are self-explanatory. 

More changes can be made to replace the rest of the explicit library-side process exits (from `src/lib.rs:56` to `src/lib.rs:75`) with more self-explanatory variants in `TrimsecError` enum, and that way error handling will be properly streamlined and the user of the library can choose what kind of messages to show (the enum can provide default error messages).

### CODE REVIEW

**Review by hitblast — APPROVED** [review]
LGTM! Changes look good. Further restructuring might help with adding more argument parsing functionality too, but let's tidy things up for v0.1.1 :3 Thanks for the contributions!

**Comment by furtidev** [comment]
Might as well use clap for CLI parsing.

**Comment by hitblast** [comment]
> Might as well use clap for CLI parsing.

Already being worked on :3

**Comment by hitblast** [comment]
@all-contributors please add @furtidev for Code

**Pull request merged**
